version: "3.7"

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    env_file:
      - .env

  synthethic_ts:
    build: .
    depends_on:
      - postgres
    restart: on-failure
    env_file:
      - .env
