version: "3.7"

services:

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: on-failure

  synthethic_ts:
    build: .
    command: ["python", "main.py", "--start-time", "${START_TIME:-2022-01-01 00:00:00}"]
    depends_on:
      - postgres
    env_file:
      - .env
    restart: on-failure
